add infoText for multiselect enum
json-editor/json-editor pull request #1075
Opened 2021-11-25 12:44 UTC by edenhaus

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Is backward-compatible?    | ✔️
| Tests pass?   | ✔️❌ Waiting for the ci to complete
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any
| Updated README/docs?   | ✔️❌ See questions
| Added CHANGELOG entry?   | ✔️❌ See questions

This PR add the feature to specify also info text for enums in an array.
As this is my first contribution to a javascript project, please let me know if I missed something.

I introduce a new option key named `enum`, which holds an array of object.
On each object you can specify:
- `title`: The title of the enum (similar to `enum_titles`)
- `infoText`: The info text showing aside the checkbox

Both keys can are optional.
`enum_titles` was the old way to specify the titles and I left it in for backwards compatibility. 

Questions:
- Should I add this feature under the "infoText" section in the readme or is there a better place?
- Should I add the changelog or is this done by the maintainer, when this PR is merged?

The schema looks like 
```json
{
  "title": "Checkbox with Infotext",
  "type": "array",
  "uniqueItems": true,
  "items": {
    "type": "string",
    "enum": ["1", "2", "3", "4", "5"],
    "options": {
      "enum_titles": ["old a", "old b"],
      "enum": [
        {},
        {
          "title": "b"
        },
        {},
        { "infoText": "dd" },
        {
          "title": "e",
          "infoText": "ee"
        }
      ]
    }
  }
}
```

2021-12-20 15:08 UTC, germanbisurgi approved these changes

2021-12-20 23:19 UTC, schmunk42 requested changes
> Should I add this feature under the "infoText" section in the readme or is there a better place?

Yes, please.

> Should I add the changelog or is this done by the maintainer, when this PR is merged?

Please add a line to the changelog.

> Should we mark enum_titles as deprecated? (Not sure if this is even possible)

I don't think we should do that, is the PR fully backward compatible?
Looks like it is, since existing tests did not change.

2021-12-21 11:22 UTC, edenhaus commented
> I don't think we should do that, is the PR fully backward compatible?

Yes it is. When both options `enum_titles[x]` and `enum[x].title` is specified for value x, than `enum[x].title` will be used. This is also written in the docs and tested by the test.

I have also added the changelog and the documentation for it

2022-01-11 15:55 UTC, schmunk42 approved these changes

2022-01-11 15:55 UTC, merged

2022-01-11 15:55 UTC, schmunk42 commented
Thank you!