Fix issue #1179
json-editor/json-editor pull request #1218
Opened 2022-10-26 02:57 UTC by lydiaaahuang

Issue: How to show enum_title selected instead of enum value in headerTemplate?

Method:
Initially, when creating an enum, there are enum options. Changed so the enum options are just the enum. Removed options.enum_title, so when creating an enum schema. e.g. the given example with the issue, the user no longer needs to put in enum options. Therefore the enum values are called in the header title. 

Original:
var schema = {
  "type": "array",
  "title": "Pets",
  "uniqueItems": false,
  "items": {
    "type": "object",
    "title": "My Pets",
    "headerTemplate": "My Pet is a \"{{self.pet}}\"",
    "properties": {
      "pet": {
        "type": "string",
        "title": "Entity",
        "default": "Contact",
        "enum": [
          "value1",
          "value2",
          "value3"
        ],
        "options": {
          "enum_titles": [
            "Dog",
            "Cat",
            "Elephant"
          ]
        }
      }
    }
  }
};

Revised:
var schema = {
  "type": "array",
  "title": "Pets",
  "uniqueItems": false,
  "items": {
    "type": "object",
    "title": "My Pets",
    "headerTemplate": "My Pet is a \"{{self.pet}}\"",
    "properties": {
      "pet": {
        "type": "string",
        "title": "Entity",
        "default": "Contact",
        "enum": [
          "Dog",
          "Cat",
          "Elephant"
        ]
      }
    }
  }
  };

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Is backward-compatible?    | ✔️❌
| Tests pass?   | ✔️
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any
| Updated README/docs?   | ❌
| Added CHANGELOG entry?   | ❌

2022-10-26 07:52 UTC, schmunk42 requested changes

2022-10-26 07:52 UTC, schmunk42 commented on package.json
> +    "@json-editor/json-editor": "^2.9.0-beta.0",
Makes no sense to depend on itself. Also there's no package update needed (no changed .lock file)

2022-10-26 11:15 UTC, lydiaaahuang commented
Just added the HTML file I used to test the schema, thought this might be helpful if not you can disregard it.

2022-10-27 11:01 UTC, schmunk42 commented
We need to think about this change since it could be viewed as a breaking change.
It would be nicer if the user can choose from displaying the value or the title.

CC: @germanbisurgi WDYT? Or is this feasible already?

2022-12-19 15:10 UTC, robocoder commented
Not only is this a breaking change, it means the behavior is no longer consistent in`editors/multiselect.js` which has a fallback from enum_titles to enum.

2024-02-12 08:17 UTC, germanbisurgi commented
Implemented in #1448

2024-02-12 08:17 UTC, closed without merging