Feature/placeholder option
json-editor/json-editor pull request #1499
Opened 2024-02-23 09:00 UTC by germanbisurgi

| Q             | A
| ------------- | ---

| New feature?  | ✔️
| Is backward-compatible?    | ✔️
| Tests pass?   | ✔️
| Updated README/docs?   | ✔️

2024-02-27 11:40 UTC, schmunk42 requested changes

2024-02-27 11:40 UTC, schmunk42 commented on README.md
Please add info about `placeholderOptionText` and a line for the CHANGELOG

2024-03-04 15:11 UTC, germanbisurgi commented
Ping

2024-03-04 16:05 UTC, schmunk42 approved these changes

2024-03-04 16:26 UTC, merged