Fix non-enum string arrays with uniqueItems
json-editor/json-editor pull request #761
Opened 2020-05-21 04:13 UTC by mattjenny

Fixes https://github.com/json-editor/json-editor/issues/735

Narrows the special case where string arrays with uniqueItems are replaced by selects to apply only if an enum is specified for array items.

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks backward-compatibility?    ❌
| Tests pass?   | ✔️
| Fixed issues  | https://github.com/json-editor/json-editor/issues/735
| Updated README/docs?   | ❌
| Added CHANGELOG entry?   | ✔️

2020-06-03 13:33 UTC, germanbisurgi commented
i don't think that the combination "uniqueItems" and "enum" was intended to be edited. I believe they are used in combination to give the user an options list to choose for and not to be able to add or remove options. It should not be editable. It looks to me that what you need is a custom validator that proves if the values in an editable array (add / remove) are unique. But i could misunderstood the problem

2020-06-03 14:19 UTC, mattjenny commented
I mostly agree -- from my reading of the code, it looks like the combination of `"uniqueItems"` and `"enum"` is a special case where the user should be provided with a non-editable list of options. However, when the `"enum"` argument is omitted, the user should be able to add new items, which was not the case with the previous logic. It's possible that the condition in [resolver.js](https://github.com/json-editor/json-editor/pull/761/files#diff-3a6ed4add80886e56c6bac48acac9a48R67) should test _only_ whether there is an enum argument, but I do think that the enum check should be a part of that condition.

2020-09-30 09:18 UTC, schmunk42 commented
@germanbisurgi are there change requests from your side?

2020-12-15 09:03 UTC, germanbisurgi commented
this was fixed in #843 with a a similar approach and same result. The tests are good. Just remove the changes to the resolver.js file and is ready to merge.

2020-12-15 10:20 UTC, germanbisurgi requested changes
See  [comment](https://github.com/json-editor/json-editor/pull/761#issuecomment-745152366)

2020-12-15 12:31 UTC, closed without merging