Openiconic iconlib
json-editor/json-editor pull request #916
Opened 2021-02-12 17:43 UTC by robocoder

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks backward-compatibility?    | ✔️
| Tests pass?   | ✔️
| Fixed issues  | 
| Updated README/docs?   | ❌
| Added CHANGELOG entry?   | ❌

I don't know if you're interested in this (seeing as the free version of openiconic hasn't been updated in quite a few years), but it's a trivial change. LMK and I'll update the examples under /docs.

2021-03-01 14:31 UTC, schmunk42 approved these changes

2021-03-01 14:32 UTC, schmunk42 requested changes
Could you add `Openiconic` to the docs and changelog, thank you.

2021-03-02 10:45 UTC, germanbisurgi approved these changes

2021-03-08 13:17 UTC, schmunk42 approved these changes

2021-03-08 13:17 UTC, merged

2021-03-08 13:17 UTC, schmunk42 commented
Thank you!